---
kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer:2.10.0@sha256:1b73755de4f19775ba6087fd5313664493e06fab72b6fc27dc2044e87bb7c4c3
    commands:
      - composer install
  - name: build
    image: php:8.5.6@sha256:f7476cffd8d6c48daa07fd80a58b85f97da095ad5a03fcf3361fd872122e3d91
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps@sha256:a376718d90e289d2d09860bf6d526bee2878f467dd61b819ec9e2c3eecc6821f
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main

