---
kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer:2.8.12@sha256:3ca62a8176c743eebef305ac2b93094a733dd5a34b5c1e3d3cf6cbbbd0792649
    commands:
      - composer install
  - name: build
    image: php:8.4.13@sha256:a627efe3590141fb90893d2db373020b67c0f297a05a92ab1e4fd2f9fb8afd86
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps@sha256:a376718d90e289d2d09860bf6d526bee2878f467dd61b819ec9e2c3eecc6821f
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main

