kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer
    commands:
      - composer install
  - name: build
    image: php:7
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /static
    when:
      event:
        exclude:
          - pull_request
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
        - success
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main
