---
kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer:2.9.8@sha256:b09bccd91a78fe8a9ab4b33d707b862e8fe54fec17782e32683ad2a69c46867d
    commands:
      - composer install
  - name: build
    image: php:8.5.6@sha256:715aaeed991350e64ba0bf4a2bf99f8859cff96d14149b6de4d48f5bef6626a8
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps@sha256:a376718d90e289d2d09860bf6d526bee2878f467dd61b819ec9e2c3eecc6821f
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main

