---
kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer:2.7.9@sha256:f4ba922bb0ede9f5ecfcfcc3f155ff4bf27bbaa4ec4f8afcc7843086960c9b5b
    commands:
      - composer install
  - name: build
    image: php:8.3.13@sha256:53ce55892af70002b5a675125a8af185ae86647c3d5bb7f4e4d687a858f6d398
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps@sha256:a376718d90e289d2d09860bf6d526bee2878f467dd61b819ec9e2c3eecc6821f
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main
---
kind: signature
hmac: 061a28030b6cd5c712e37174483ba6484ab67fe2f47a9053d47c39e2ebe6a639

...
