---
kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: composer:2.8.4@sha256:158fcf22c9403c64a2433af7100295a4db86bec35fa3aca8c7c5e29edbe0869f
    commands:
      - composer install
  - name: build
    image: php:8.3.15@sha256:4b5533da7a0396ca147c1b323ce78ef564a9c89c830c394ea25050da51ab83fe
    commands:
      - ./vendor/bin/daux generate
  - name: deploy
    image: cschlosser/drone-ftps@sha256:a376718d90e289d2d09860bf6d526bee2878f467dd61b819ec9e2c3eecc6821f
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /static
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main

